# Generated by Django 5.0.7 on 2025-08-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('neft', 'Neft')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('delivery', models.CharField(blank=True, max_length=200)),
                ('volume', models.CharField(blank=True, max_length=100)),
                ('quality', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product')),
            ],
        ),
    ]
