# Generated by Django 5.0.7 on 2025-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='TelegramRelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_chat_id', models.BigIntegerField()),
                ('forwarded_message_id', models.BigIntegerField()),
                ('user_chat_id', models.BigIntegerField()),
                ('user_username', models.CharField(blank=True, max_length=255)),
                ('user_first_name', models.CharField(blank=True, max_length=255)),
                ('user_last_name', models.CharField(blank=True, max_length=255)),
                ('user_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['admin_chat_id', 'forwarded_message_id'], name='api_telegra_admin_c_87f66b_idx')],
            },
        ),
    ]
