# Generated by Django 5.0.7 on 2025-08-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramRelay',
        ),
    ]
