Microsoft Windows [Version 10.0.26100.6584]
(c) Microsoft Corporation. All rights reserved.

C:\Users\volto\StartPetrol-website>

C:\Users\volto\StartPetrol-website>[main eb7ed74] Fix frontend Dockerfile content
 1 file changed, 4 insertions(+), 20 deletions(-)

C:\Users\volto\StartPetrol-website>

C:\Users\volto\StartPetrol-website>
C:\Users\volto\StartPetrol-website>