services:
  backend:
    build: ./backend
    container_name: startpetrol_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: startpetrol_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  bot:
    build: ./bot
    container_name: startpetrol_bot
    env_file:
      - ./bot/.env
    restart: always
